### ISSUE TITLE
Sorting identifiers

### ISSUE THREAD

**Issue by Alex9779** [tohara/OctoPrint-BigBoxFirmware#2]
In a profile it would be great if the identifiers could be sorted.
When creating a profile you will not set every setting. If you base a second profile on a copy of an existing all settings are added to the bottom which makes it difficult to see which settings you already have and which not.

Even better would be if you could "compare" your identifiers to the configuration files of Marlin and sort them automatically in the order they appear in the config files.

This could also be used to keep the identifiers up to date if Marlin removes or renames identifiers. They then could be highlighted so you can take actions...

**Comment by tohara** [comment]
I like this suggestion and are looking into it. I don't have much time to spend on this at the moment, so it might take a while.

**Comment by Alex9779** [comment]
No problem. Take the time you need use wanted to have the idea logged ;)

**Comment by tohara** [comment]
I have now added sorting of the identifiers according to the order they appear in the config files. 

Any identifiers not found will be marked red and stay on top.

But I am not too happy with the performance, it takes a bit to long for the server to respond some times. Looking in to how it can be optimized.

But for now the latest changes is pushed to the dev branch.

**Comment by tohara** [comment]
I have changed the generation of the define list to only be run when a new repo is added or updated. After updating to latest version you need to run an update of all existing repos.

**Comment by Alex9779** [comment]
As far as I can tell this works as intended... Nice work!
