### ISSUE TITLE
Repository update

### ISSUE THREAD

**Issue by Alex9779** [tohara/OctoPrint-BigBoxFirmware#3]
Is the repository updated before even build?
It seems not, I think I have to go to the repo management screen and "Fore update".

I have no idea if it would be good to do it before every compile... Is that possible???

**Comment by tohara** [comment]
When running a build it runs a force checkout of the selected branch. Nothing is pulled from remote.

I would be easy to update the repository before every build by running a force pull, but not sure if we want that?

My thought was that if I have added a repository and have a working firmware I would like to preserve that state until I choose to update.

**Comment by Alex9779** [comment]
Yeah ok, I was sure you thought about that but I wanted to know why... You got a point there...
For me it is just more click work when experimenting with firmwares to get the repo updated.

**Comment by tohara** [comment]
Maybe I could add a tickbox for setting "Auto Update"?

**Comment by Alex9779** [comment]
To the profile? Or the repo?

**Comment by tohara** [comment]
I think it would make most sense to have it in the repo manager.

**Comment by tohara** [comment]
A checkbox has been added in the repo manager for every repo. Checking this will trigger a hard reset of selected branch to origin before every build.
