### ISSUE TITLE
Export/Import profiles

### ISSUE THREAD

**Issue by Alex9779** [tohara/OctoPrint-BigBoxFirmware#4]
The default profiles are fine but it would be great if we could export or import profiles from the GUI so exchanging profiles with others maybe not so experienced users would be much easier...

**Comment by tohara** [comment]
This has been on my list as a new feature when I get the initial version working:)

Each profile is just a json file under ~/.octoprint/data/bigboxfirmware/profiles

**Comment by Alex9779** [comment]
Hehe I knew you thought about this... I didn't dig into it yet too deep but I thought they must be in there in some way... One file for profile is cool, could also have been one huge file but you designed it with something in your mind, that's perfect...
Ok so closing here now as it is already on your list... Waiting desperately :;
