### ISSUE TITLE
update for latest RCBugFix (20170408)

### ISSUE THREAD

**Issue by autonumous** [tohara/OctoPrint-BigBoxFirmware#7]
fix for latest RCBugFix branch
Details: https://github.com/MarlinFirmware/Marlin/pull/5994/commits
Not tested with any other build

lib/Makefile: Line 183
from
`CEXTRA = -fno-use-cxa-atexit`
to 
`CEXTRA = -fno-use-cxa-atexit  -fno-threadsafe-statics`

**Comment by tohara** [comment]
Merged
